import { useDraggable, useDroppable } from '@dnd-kit/core';
import { Badge, Button, cn } from '@cnma/react-ui';
import { ChevronDown, ChevronUp, GripVertical, LayoutGrid, Plus, Trash2, X } from 'lucide-react';
import type { FormFieldConfig, FormGroupConfig, FormSpacerConfig } from '../types';

function CanvasField({ field, columns, selected, first, last, onSelect, onRemove, onMove }: { field: FormFieldConfig; columns: number; selected: boolean; first: boolean; last: boolean; onSelect: () => void; onRemove: () => void; onMove: (direction: -1 | 1) => void }) {
    const drag = useDraggable({ id: `field-${field.key}` }); const drop = useDroppable({ id: `field-${field.key}` });
    const setRef = (node: HTMLElement | null) => { drag.setNodeRef(node); drop.setNodeRef(node); };
    const legacySpan = field.width === '100%' ? columns : field.width === '50%' ? Math.max(1, Math.ceil(columns / 2)) : field.width === '33%' ? Math.max(1, Math.ceil(columns / 3)) : 1;
    return <div ref={setRef} style={{ gridColumn: `span ${Math.min(field.colSpan ?? legacySpan, columns)}`, gridRow: (field.rowSpan ?? 1) > 1 ? `span ${field.rowSpan}` : undefined }} className={cn('group relative flex min-h-9 h-auto select-none cursor-pointer items-start gap-2 rounded-md border px-2.5 py-2 text-xs transition-all', selected ? 'border-info bg-info-bg shadow-sm' : 'border-border bg-background hover:border-info/30 hover:bg-accent', drop.isOver && !drag.isDragging && 'border-primary bg-primary/5 ring-2 ring-primary/50', drag.isDragging && 'opacity-30 border-dashed')} onClick={(event) => { event.stopPropagation(); onSelect(); }}>
        <span {...drag.attributes} {...drag.listeners} className="mt-0.5 cursor-grab text-muted-foreground hover:text-foreground touch-none"><GripVertical className="h-3.5 w-3.5 shrink-0" /></span>
        <span className="min-w-0 flex-1 font-medium leading-normal break-words whitespace-normal text-foreground">{field.label ?? field.key}</span>
        {field.visible === false && <Badge variant="outline" className="mt-0.5 text-[10px] px-1 py-0">Hidden</Badge>}
        <div className="hidden items-center gap-0.5 group-hover:flex self-start"><Button variant="ghost" size="icon" className="h-6 w-6" disabled={first} onClick={(event) => { event.stopPropagation(); onMove(-1); }}><ChevronUp className="h-3 w-3" /></Button><Button variant="ghost" size="icon" className="h-6 w-6" disabled={last} onClick={(event) => { event.stopPropagation(); onMove(1); }}><ChevronDown className="h-3 w-3" /></Button><Button variant="ghost" size="icon" className="h-6 w-6" onClick={(event) => { event.stopPropagation(); onRemove(); }}><X className="h-3 w-3" /></Button></div>
    </div>;
}

function Spacer({ spacer, columns, onDelete }: { spacer: FormSpacerConfig; columns: number; onDelete: () => void }) {
    return <div style={{ gridColumn: `span ${Math.min(spacer.colSpan, columns)}` }} className="flex h-9 items-center justify-between rounded-md border border-dashed bg-muted/30 px-2 text-xs text-muted-foreground"><span>Spacer · {spacer.height}</span><Button variant="ghost" size="icon" className="h-6 w-6" onClick={onDelete}><X className="h-3 w-3" /></Button></div>;
}

interface CanvasGroupProps { group: FormGroupConfig; fields: FormFieldConfig[]; spacers: FormSpacerConfig[]; index: number; count: number; selectedField: string | null; selectedGroup: string | null; overId: string | null; onSelectField: (key: string) => void; onSelectGroup: () => void; onRemoveField: (key: string) => void; onDeleteGroup: () => void; onMoveGroup: (direction: -1 | 1) => void; onMoveField: (key: string, direction: -1 | 1) => void; onAddSpacer: () => void; onDeleteSpacer: (id: string) => void }

function CanvasGroup(props: CanvasGroupProps) {
    const { group, fields, spacers, index, count, selectedField, selectedGroup, overId } = props; const drop = useDroppable({ id: `group-${group.id}` }); const columns = group.columns ?? 2;
    const isGroupOver = drop.isOver || overId === `group-${group.id}`;
    return <section ref={drop.setNodeRef} className={cn('rounded-lg border-2 bg-background/80 transition-all shadow-xs', isGroupOver ? 'border-info bg-info-bg/50 ring-2 ring-info/30' : selectedGroup === group.id ? 'border-primary shadow-sm' : 'border-border hover:border-muted-foreground/30')} onClick={props.onSelectGroup}>
        <div className="flex items-center justify-between rounded-t-lg border-b bg-muted/30 px-3 py-2"><div className="flex items-center gap-2"><GripVertical className="h-3.5 w-3.5 text-muted-foreground" /><div><div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{group.label}</div><div className="text-[11px] text-muted-foreground/80">{group.width ?? '100'}% · {columns} cols · {fields.length} fields</div></div></div><div className="flex items-center gap-0.5"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={(event) => { event.stopPropagation(); props.onAddSpacer(); }}><Plus className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7" disabled={index === 0} onClick={(event) => { event.stopPropagation(); props.onMoveGroup(-1); }}><ChevronUp className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7" disabled={index === count - 1} onClick={(event) => { event.stopPropagation(); props.onMoveGroup(1); }}><ChevronDown className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-destructive hover:text-destructive" onClick={(event) => { event.stopPropagation(); props.onDeleteGroup(); }}><Trash2 className="h-3.5 w-3.5" /></Button></div></div>
        <div className="grid min-h-16 auto-rows-min gap-1.5 p-2" style={{ gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))`, gridAutoFlow: 'dense' }}>{fields.map((field, fieldIndex) => <CanvasField key={field.key} field={field} columns={columns} selected={selectedField === field.key} first={fieldIndex === 0} last={fieldIndex === fields.length - 1} onSelect={() => props.onSelectField(field.key)} onRemove={() => props.onRemoveField(field.key)} onMove={(direction) => props.onMoveField(field.key, direction)} />)}{spacers.map((spacer) => <Spacer key={spacer.id} spacer={spacer} columns={columns} onDelete={() => props.onDeleteSpacer(spacer.id)} />)}{!fields.length && !spacers.length && <div className="col-span-full flex min-h-16 items-center justify-center rounded border border-dashed border-muted-foreground/30 bg-muted/20 text-xs text-muted-foreground">Drop fields here</div>}</div>
    </section>;
}

interface LayoutCanvasPanelProps { groups: FormGroupConfig[]; allFields: FormFieldConfig[]; spacers: FormSpacerConfig[]; selectedField: string | null; selectedGroup: string | null; overId: string | null; onSelectField: (key: string) => void; onSelectGroup: (id: string) => void; onRemoveField: (key: string) => void; onDeleteGroup: (id: string) => void; onMoveGroup: (id: string, direction: -1 | 1) => void; onMoveField: (groupId: string, key: string, direction: -1 | 1) => void; onAddSpacer: (groupId: string) => void; onDeleteSpacer: (id: string) => void }

export function LayoutCanvasPanel(props: LayoutCanvasPanelProps) {
    const canvasDrop = useDroppable({ id: 'canvas' });
    const isCanvasOver = canvasDrop.isOver || props.overId === 'canvas';
    return <main ref={canvasDrop.setNodeRef} className={cn('min-w-0 flex-1 overflow-y-auto bg-muted/20 p-4 transition-colors', isCanvasOver && 'bg-info-bg/20 ring-2 ring-inset ring-info/20')}><div className="mx-auto flex max-w-5xl flex-wrap items-start gap-3 min-h-full">{props.groups.map((index, groupIndex) => <div key={index.id} className="min-w-64 flex-1" style={{ flexBasis: `${index.width ?? '100'}%` }}><CanvasGroup group={index} fields={index.fieldKeys.map((key) => props.allFields.find((field) => field.key === key)).filter((field): field is FormFieldConfig => Boolean(field))} spacers={props.spacers.filter((spacer) => spacer.groupId === index.id)} index={groupIndex} count={props.groups.length} selectedField={props.selectedField} selectedGroup={props.selectedGroup} overId={props.overId} onSelectField={props.onSelectField} onSelectGroup={() => props.onSelectGroup(index.id)} onRemoveField={props.onRemoveField} onDeleteGroup={() => props.onDeleteGroup(index.id)} onMoveGroup={(direction) => props.onMoveGroup(index.id, direction)} onMoveField={(key, direction) => props.onMoveField(index.id, key, direction)} onAddSpacer={() => props.onAddSpacer(index.id)} onDeleteSpacer={props.onDeleteSpacer} /></div>)}{!props.groups.length && <div className={cn('flex min-h-80 w-full flex-col items-center justify-center rounded-xl border-2 border-dashed bg-background p-6 text-center text-muted-foreground transition-colors', isCanvasOver && 'border-info bg-info-bg/30 text-info')}><LayoutGrid className="mb-3 h-10 w-10 opacity-40" /><p className="font-semibold text-base text-foreground">No layout groups</p><p className="mt-1 text-sm">Drag fields here to create a group, or click "Add group" on the left.</p></div>}</div></main>;
}
