import { useDraggable, useDroppable } from '@dnd-kit/core';
import { Badge, Button, cn } from '@cnma/react-ui';
import { ChevronDown, ChevronUp, GripVertical, LayoutGrid, Plus, Trash2, X } from 'lucide-react';
import type { FormFieldConfig, FormGroupConfig, FormSpacerConfig } from '../types';

function CanvasField({ field, columns, selected, first, last, onSelect, onRemove, onMove }: { field: FormFieldConfig; columns: number; selected: boolean; first: boolean; last: boolean; onSelect: () => void; onRemove: () => void; onMove: (direction: -1 | 1) => void }) {
    const drag = useDraggable({ id: `field-${field.key}` }); const drop = useDroppable({ id: `field-${field.key}` });
    const setRef = (node: HTMLElement | null) => { drag.setNodeRef(node); drop.setNodeRef(node); };
    const legacySpan = field.width === '100%' ? columns : field.width === '50%' ? Math.max(1, Math.ceil(columns / 2)) : field.width === '33%' ? Math.max(1, Math.ceil(columns / 3)) : 1;
    return <div ref={setRef} style={{ gridColumn: `span ${Math.min(field.colSpan ?? legacySpan, columns)}`, gridRow: (field.rowSpan ?? 1) > 1 ? `span ${field.rowSpan}` : undefined }} className={cn('group relative flex cursor-pointer items-center gap-1.5 rounded border p-1.5 text-xs transition-all', selected ? 'border-info bg-info-bg shadow-sm' : 'border-border bg-background hover:border-info/30 hover:bg-accent', drop.isOver && !drag.isDragging && 'border-primary bg-primary/5 ring-2 ring-primary/50', drag.isDragging && 'opacity-30')} onClick={(event) => { event.stopPropagation(); onSelect(); }}>
        <span {...drag.attributes} {...drag.listeners} className="cursor-grab text-muted-foreground"><GripVertical className="h-3 w-3" /></span><span className="min-w-0 flex-1 truncate font-medium">{field.label ?? field.key}</span>{field.visible === false && <Badge variant="outline">Hidden</Badge>}
        <div className="hidden items-center gap-0.5 group-hover:flex"><Button variant="ghost" size="icon" disabled={first} onClick={(event) => { event.stopPropagation(); onMove(-1); }}><ChevronUp className="h-3 w-3" /></Button><Button variant="ghost" size="icon" disabled={last} onClick={(event) => { event.stopPropagation(); onMove(1); }}><ChevronDown className="h-3 w-3" /></Button><Button variant="ghost" size="icon" onClick={(event) => { event.stopPropagation(); onRemove(); }}><X className="h-3 w-3" /></Button></div>
    </div>;
}

function Spacer({ spacer, columns, onDelete }: { spacer: FormSpacerConfig; columns: number; onDelete: () => void }) {
    return <div style={{ gridColumn: `span ${Math.min(spacer.colSpan, columns)}` }} className="flex min-h-10 items-center justify-between rounded border border-dashed bg-muted/30 px-2 text-xs text-muted-foreground"><span>Spacer · {spacer.height}</span><Button variant="ghost" size="icon" onClick={onDelete}><X className="h-3 w-3" /></Button></div>;
}

interface CanvasGroupProps { group: FormGroupConfig; fields: FormFieldConfig[]; spacers: FormSpacerConfig[]; index: number; count: number; selectedField: string | null; selectedGroup: string | null; overId: string | null; onSelectField: (key: string) => void; onSelectGroup: () => void; onRemoveField: (key: string) => void; onDeleteGroup: () => void; onMoveGroup: (direction: -1 | 1) => void; onMoveField: (key: string, direction: -1 | 1) => void; onAddSpacer: () => void; onDeleteSpacer: (id: string) => void }

function CanvasGroup(props: CanvasGroupProps) {
    const { group, fields, spacers, index, count, selectedField, selectedGroup, overId } = props; const drop = useDroppable({ id: `group-${group.id}` }); const columns = group.columns ?? 2;
    return <section ref={drop.setNodeRef} className={cn('rounded-lg border-2 bg-background/80 transition-all', drop.isOver || overId === `group-${group.id}` ? 'border-info bg-info-bg/50 ring-2 ring-info/30' : selectedGroup === group.id ? 'border-primary shadow-sm' : 'border-border hover:border-muted-foreground/30')} onClick={props.onSelectGroup}>
        <div className="flex items-center justify-between rounded-t-lg border-b bg-muted/30 p-2"><div className="flex items-center gap-2"><GripVertical className="h-3 w-3 text-muted-foreground" /><div><div className="text-xs font-semibold uppercase text-muted-foreground">{group.label}</div><div className="text-xs text-muted-foreground">{group.width ?? '100'}% · {columns} cols · {fields.length} fields</div></div></div><div className="flex items-center gap-0.5"><Button variant="ghost" size="icon" onClick={(event) => { event.stopPropagation(); props.onAddSpacer(); }}><Plus className="h-3 w-3" /></Button><Button variant="ghost" size="icon" disabled={index === 0} onClick={(event) => { event.stopPropagation(); props.onMoveGroup(-1); }}><ChevronUp className="h-3 w-3" /></Button><Button variant="ghost" size="icon" disabled={index === count - 1} onClick={(event) => { event.stopPropagation(); props.onMoveGroup(1); }}><ChevronDown className="h-3 w-3" /></Button><Button variant="ghost" size="icon" onClick={(event) => { event.stopPropagation(); props.onDeleteGroup(); }}><Trash2 className="h-3 w-3 text-destructive" /></Button></div></div>
        <div className="grid min-h-16 auto-rows-min gap-1 p-2" style={{ gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))`, gridAutoFlow: 'dense' }}>{fields.map((field, fieldIndex) => <CanvasField key={field.key} field={field} columns={columns} selected={selectedField === field.key} first={fieldIndex === 0} last={fieldIndex === fields.length - 1} onSelect={() => props.onSelectField(field.key)} onRemove={() => props.onRemoveField(field.key)} onMove={(direction) => props.onMoveField(field.key, direction)} />)}{spacers.map((spacer) => <Spacer key={spacer.id} spacer={spacer} columns={columns} onDelete={() => props.onDeleteSpacer(spacer.id)} />)}{!fields.length && !spacers.length && <div className="col-span-full flex min-h-14 items-center justify-center text-xs text-muted-foreground">Drop fields here</div>}</div>
    </section>;
}

interface LayoutCanvasPanelProps { groups: FormGroupConfig[]; allFields: FormFieldConfig[]; spacers: FormSpacerConfig[]; selectedField: string | null; selectedGroup: string | null; overId: string | null; onSelectField: (key: string) => void; onSelectGroup: (id: string) => void; onRemoveField: (key: string) => void; onDeleteGroup: (id: string) => void; onMoveGroup: (id: string, direction: -1 | 1) => void; onMoveField: (groupId: string, key: string, direction: -1 | 1) => void; onAddSpacer: (groupId: string) => void; onDeleteSpacer: (id: string) => void }

export function LayoutCanvasPanel(props: LayoutCanvasPanelProps) {
    return <main className="min-w-0 flex-1 overflow-y-auto bg-muted/20 p-4"><div className="mx-auto flex max-w-5xl flex-wrap items-start gap-3">{props.groups.map((group, index) => <div key={group.id} className="min-w-64 flex-1" style={{ flexBasis: `${group.width ?? '100'}%` }}><CanvasGroup group={group} fields={group.fieldKeys.map((key) => props.allFields.find((field) => field.key === key)).filter((field): field is FormFieldConfig => Boolean(field))} spacers={props.spacers.filter((spacer) => spacer.groupId === group.id)} index={index} count={props.groups.length} selectedField={props.selectedField} selectedGroup={props.selectedGroup} overId={props.overId} onSelectField={props.onSelectField} onSelectGroup={() => props.onSelectGroup(group.id)} onRemoveField={props.onRemoveField} onDeleteGroup={() => props.onDeleteGroup(group.id)} onMoveGroup={(direction) => props.onMoveGroup(group.id, direction)} onMoveField={(key, direction) => props.onMoveField(group.id, key, direction)} onAddSpacer={() => props.onAddSpacer(group.id)} onDeleteSpacer={props.onDeleteSpacer} /></div>)}{!props.groups.length && <div className="flex min-h-80 w-full flex-col items-center justify-center rounded-xl border border-dashed bg-background text-center text-muted-foreground"><LayoutGrid className="mb-3 h-10 w-10 opacity-30" /><p className="font-medium">No layout groups</p><p className="text-sm">Create a group, then drag fields into it.</p></div>}</div></main>;
}
